### ISSUE TITLE
Posible problema

### ISSUE THREAD

**Issue by ArielRobotti** [Juan-Fuente-T/NotPonzi_Banckathon#3]
https://github.com/Juan-Fuente-T/NotPonzi_Banckathon/blob/af1b639362eb59212ef089423a6e7bc61ecec653/foundry/src/Towerbank.sol#L127
Según veo, en este if no se entraria nunca ya que el valor no puede ser menor que cero y mayor que 1000 al mismo tiempo.
Un valor de entrada de 10000 setearia feeBuyer en 10000 y consecuentemente el ammountFeeBuyer calculado en la linea 268 sería el 100 % de scrow.value. Sugerencia: Reemplazar && por ||

**Comment by Juaan-Dvid** [comment]
Solucionado.
