### ISSUE TITLE
Problema en el constructor

### ISSUE THREAD

**Issue by ArielRobotti** [Juan-Fuente-T/NotPonzi_Banckathon#4]
https://github.com/Juan-Fuente-T/NotPonzi_Banckathon/blob/14fa144865e31a624b15a7d83fcf5424924ca6fd/foundry/src/Towerbank.sol#L101
 Cuando se ejecutan estas llamas a setear los fees, la variable maxFeeAllowed aun no tiene un valor definido ( no recuerdo si en solidity cuando no se inicializa una variable toma el valor 0).
Ambas funciones (setFeeSeller y setFeeBuyer) llaman internamente a _feeValidation y esta funcion impide que el fee que se intenta establecer sea mayor que maxFeeAllowed que no está inicializada en la construcción. Armo el test y confirmo si falla

**Comment by ArielRobotti** [comment]
Solucion: Mover la linea `maxFeeAllowed = _maxFeeAllowed;` hacia arriba de las llamadas `setFeeBuyer(_newFeeBuyer);
        setFeeSeller(_newFeeSeller);`

**Comment by Juaan-Dvid** [comment]
He movido las dos variables para que se le asignen valor antes de que sean llamadas:

constructor(address _token, uint256 _newFeeSeller, uint256 _newFeeBuyer, uint256 _maxFeeAllowed, uint256 _percentageDivisor) {
        whitelistToken[_token] = true;
        maxFeeAllowed = _maxFeeAllowed;
        percentageDivisor = _percentageDivisor;
        setFeeSeller(_newFeeSeller);
        setFeeBuyer(_newFeeBuyer);                
    }
