### ISSUE TITLE
Se pueden agregar address que no son de Tokens

### ISSUE THREAD

**Issue by ArielRobotti** [Juan-Fuente-T/NotPonzi_Banckathon#5]
https://github.com/Juan-Fuente-T/NotPonzi_Banckathon/blob/14fa144865e31a624b15a7d83fcf5424924ca6fd/foundry/src/Towerbank.sol#L359

Se podria armar una funcion que verifique que la address ingresada corresponde a un ERC 20. Dentro de la cual se llame a alguna funcion existentes en ese standard. Ejemplo:
```
function isERC20(address tokenAddress) public view returns (bool) {
    try IERC20(tokenAddress).totalSupply() {
        return true;
    } catch {
        return false;
    }
 }
```

**Comment by Juaan-Dvid** [comment]
Tengamolo en cuenta para mas adelante

**Comment by ArielRobotti** [comment]
Cierro esta y dejé tres relacionadas con esto mismo. Una para declarar el error, otra para definir la funcion de comprobacion y la ultima para agregar la comprobacion en la funcion addTokenToWhiteList(). En la funcion delete no es necesario

**Comment by ArielRobotti** [comment]
Cierro esta y dejé tres relacionadas con esto mismo. Una para declarar el error, otra para definir la funcion de comprobacion y la ultima para agregar la comprobacion en la funcion addTokenToWhiteList(). En la funcion delete no es necesario
